name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run
      run: dotnet run
    - name: Display structure of the files
      run: ls -R
      working-directory: /home/runner/work/WAParcels/WAParcels/bin/Debug/net5.0/
    - uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/WAParcels/WAParcels/bin/Debug/net5.0/WA
